/* FlashFusion Agent Console — data layer */
window.FF = (function () {

  // ---- Domains ----
  const DOMAINS = {
    orchestration:        { label: "Orchestration",      hue: "accent", blurb: "Routing, architecture & system integrity" },
    "build-infra":        { label: "Build & Infra",      hue: "teal",   blurb: "Code, data, tests & delivery" },
    "security-risk":      { label: "Security & Risk",     hue: "rose",   blurb: "AppSec, compliance & AI governance" },
    "reliability-insights": { label: "Reliability & Insight", hue: "warm", blurb: "SLOs, experiments & strategy" },
    "knowledge-innovation": { label: "Knowledge",         hue: "acid",   blurb: "Memory, patterns & learning" },
    "customer-market":    { label: "Customer",            hue: "accent", blurb: "Support, research & the user's voice" },
  };

  // ---- Agents ----
  // status: active | idle | standby | blocked | queued
  const AGENTS = [
    { id:"tessa", name:"Tessa", role:"Master Orchestrator", framework:"RAIN", domain:"orchestration",
      glyph:"◎", status:"active", now:"Routing PR #2241 → Forge",
      identity:"The air-traffic controller. Decides which agent does what, in what order, with what context handoff. Optimizes for throughput and unambiguous handoffs — never writes code, deploys, or audits.",
      tools:["context7","linear","github","slack"],
      triggers:["multi-agent workflow","cross-team coordination","complex routing","@tessa"],
      escalates:["agent-k","conductor"],
      perms:{ read:["linear","github","slack","notion"], write:["linear","slack"], execute:["—"] } },

    { id:"agent-k", name:"Agent K", role:"Omnipotent Executor", framework:"RAPID", domain:"orchestration",
      glyph:"⚡", status:"standby", now:"No active incidents · armed",
      identity:"The firefighter. Invoked only when the building is on fire. Holds full production access because the cost of asking is higher than the cost of doing. Leaves a paper trail for everything.",
      tools:["vercel","supabase","stripe","cloudflare","github","sentry","datadog"],
      triggers:["P0","P1","incident","outage","rollback now","SLO breach"],
      escalates:["human-on-call"],
      perms:{ read:["all"], write:["all"], execute:["rollback","kill-switch","traffic-shift"] } },

    { id:"conductor", name:"Conductor", role:"System Architect", framework:"ALIGN", domain:"orchestration",
      glyph:"❖", status:"active", now:"Drafting ADR-038 · queue backend",
      identity:"Owns the shape of the system, not the code. Decides what services exist, how they communicate, where state lives, and what counts as done architecturally. Produces ADRs, not pull requests.",
      tools:["github","linear","notion","figma","context7"],
      triggers:["architecture decision","ADR","system design","should we use","quarterly planning"],
      escalates:["human-staff-engineer"],
      perms:{ read:["all"], write:["notion","linear","github-issues"], execute:["—"] } },

    { id:"sentinel", name:"Sentinel", role:"MCP Governance", framework:"GUARD", domain:"orchestration",
      glyph:"◈", status:"idle", now:"Next agent review in 6d",
      identity:"The agent system's quality gate. Reviews other agents' specs, audits their tool permissions, and prevents prompt drift. Paranoid by design.",
      tools:["github","notion","context7"],
      triggers:["agent prompt drift","MCP server change","quarterly agent review","@sentinel"],
      escalates:["conductor"],
      perms:{ read:["all-agent-files","mcp-configs"], write:["agent-files","mcp-configs"], execute:["—"] } },

    { id:"forge", name:"Forge", role:"Code Generation", framework:"BUILD", domain:"build-infra",
      glyph:"⛭", status:"active", now:"PR #2241 · 3 files +84 −12",
      identity:"Writes production code. Produces small, reviewable diffs. Does not architect, deploy, or test in production. Takes ADRs as input and produces PRs as output.",
      tools:["github","linear","typescript","next.js","prisma","context7"],
      triggers:["implement","build feature","write code","scaffold","@forge"],
      escalates:["conductor","inspector","guardian"],
      perms:{ read:["github","linear","notion"], write:["github-branches","github-prs"], execute:["npm-test","type-check","lint"] } },

    { id:"atlas", name:"Atlas", role:"Data Architect", framework:"DATA", domain:"build-infra",
      glyph:"▦", status:"active", now:"Migration 0042 staged",
      identity:"Owns the database schema and access patterns. Writes migrations and RLS policies. Does not write application code that uses the schema — routes that to Forge.",
      tools:["prisma","supabase","postgresql","pganalyze"],
      triggers:["schema","migration","RLS","query optimization","data model","@atlas"],
      escalates:["conductor","guardian"],
      perms:{ read:["database-schemas","query-logs"], write:["migrations","rls-policies","indexes"], execute:["migration-staging","migration-prod (approval)"] } },

    { id:"inspector", name:"Inspector", role:"Quality Engineer", framework:"VALIDATE", domain:"build-infra",
      glyph:"⊞", status:"active", now:"e2e suite · 142/160 passing",
      identity:"Writes tests and enforces quality gates. Does not write application code. Blocks deploys when coverage falls or critical paths regress.",
      tools:["vitest","playwright","codecov","sonarqube"],
      triggers:["test","coverage","regression","QA","@inspector"],
      escalates:["forge","pipeline"],
      perms:{ read:["github","test-results","coverage-reports"], write:["test-files"], execute:["test-run","coverage-check"] } },

    { id:"pipeline", name:"Pipeline", role:"Deploy & Environment", framework:"SHIP", domain:"build-infra",
      glyph:"⇲", status:"queued", now:"Awaiting Inspector gate · web@prod",
      identity:"Owns CI/CD. Does not write application code. Ensures what passed locally passes in CI, that staging mirrors production, and that every deploy is reversible.",
      tools:["vercel","github-actions","sentry","datadog","cloudflare"],
      triggers:["deploy","rollback","release","feature flag","PR merged to main"],
      escalates:["agent-k","watchtower"],
      perms:{ read:["github","vercel","env (non-secret)"], write:["vercel-deploys","actions-config"], execute:["deploy","rollback","traffic-shift"] } },

    { id:"guardian", name:"Guardian", role:"Application Security", framework:"SHIELD", domain:"security-risk",
      glyph:"⛨", status:"active", now:"Scanning PR #2241 · 0 criticals",
      identity:"Reviews code for security weaknesses, scans dependencies, audits secrets handling. Blocks PRs that introduce vulnerabilities. Writes incident reports for confirmed issues.",
      tools:["snyk","semgrep","owasp-zap","sentry","gitleaks"],
      triggers:["security review","vulnerability","OWASP","auth","secret","@guardian"],
      escalates:["agent-k","prime"],
      perms:{ read:["github","sentry","audit-logs"], write:["security-issues","pr-reviews"], execute:["security-scan","dependency-check"] } },

    { id:"prime", name:"Prime", role:"Risk & Compliance", framework:"COMPLY", domain:"security-risk",
      glyph:"✦", status:"idle", now:"SOC2 evidence fresh · 12d old",
      identity:"Owns the compliance posture. Collects evidence continuously, maintains policies, and prepares for audits. Translates regulatory requirements into engineering tasks.",
      tools:["vanta","drata","supabase","datadog","notion"],
      triggers:["SOC2","GDPR","HIPAA","PCI-DSS","ISO 42001","EU AI Act","compliance","audit"],
      escalates:["conductor","guardian","human-counsel"],
      perms:{ read:["audit-logs","access-logs","configuration"], write:["compliance-evidence","policy-docs"], execute:["evidence-collection"] } },

    { id:"ethica", name:"Ethica", role:"AI Governance", framework:"ETHIC", domain:"security-risk",
      glyph:"☯", status:"idle", now:"No AI features in review",
      identity:"Reviews AI features for safety, bias, and policy alignment. The bridge between “the model can do this” and “we should let it do this in production.”",
      tools:["openai-moderation","perspective-api","fairlearn","langfuse"],
      triggers:["AI feature","model deploy","content moderation","bias","harmful output","EU AI Act"],
      escalates:["prime","conductor"],
      perms:{ read:["model-outputs","prompt-logs","training-metadata"], write:["ai-policy-docs","moderation-rules"], execute:["bias-audit","content-scan"] } },

    { id:"watchtower", name:"Watchtower", role:"Reliability & Performance", framework:"MONITOR", domain:"reliability-insights",
      glyph:"◬", status:"active", now:"All SLOs green · p95 218ms",
      identity:"Defines what “healthy” means and detects when reality drifts from it. Owns SLOs, dashboards, alerting, and on-call routing.",
      tools:["datadog","sentry","prometheus","grafana","opentelemetry"],
      triggers:["SLO","latency","error rate","performance regression","alert fired"],
      escalates:["agent-k","forge"],
      perms:{ read:["metrics","logs","traces"], write:["dashboards","alerts","slo-config"], execute:["alert-fire","runbook-trigger"] } },

    { id:"validator", name:"Validator", role:"Experimentation", framework:"TESTLOOP", domain:"reliability-insights",
      glyph:"⟁", status:"active", now:"exp-checkout-v3 · 51% → 94% conf",
      identity:"Runs experiments. Does not write features. Decides whether a launched feature actually moved the needle, with statistical rigor.",
      tools:["posthog","statsig","growthbook","datadog"],
      triggers:["A/B test","experiment","feature flag","rollout","@validator"],
      escalates:["strategos","ethica"],
      perms:{ read:["event-data","user-cohorts"], write:["feature-flags","experiment-configs"], execute:["experiment-launch","experiment-stop"] } },

    { id:"strategos", name:"Strategos", role:"Strategy & Business", framework:"STRATEGIC", domain:"reliability-insights",
      glyph:"➶", status:"idle", now:"Q3 OKRs locked · NSM +4.1%",
      identity:"Translates business goals into measurable objectives. Owns OKRs, the North Star metric, and the quarterly roadmap. Does not run experiments or define architecture.",
      tools:["notion","linear","posthog","stripe","amplitude"],
      triggers:["OKR","strategy","north star","roadmap","quarterly planning"],
      escalates:["conductor","human-leadership"],
      perms:{ read:["revenue","user-metrics","market-data"], write:["okr-docs","strategy-docs"], execute:["—"] } },

    { id:"archivist", name:"Archivist", role:"Knowledge & Innovation", framework:"LEARN", domain:"knowledge-innovation",
      glyph:"❡", status:"idle", now:"Logging ADR-037 to library",
      identity:"Captures what the team learned. Writes post-mortems, maintains the pattern library, and keeps documentation honest. Prevents the same lesson from being learned twice.",
      tools:["notion","confluence","context7","github"],
      triggers:["post-mortem","documentation","knowledge","learning","pattern","@archivist"],
      escalates:["conductor"],
      perms:{ read:["all-docs","post-mortems","adrs"], write:["docs","learning-log","pattern-library"], execute:["—"] } },

    { id:"ambassador", name:"Ambassador", role:"Customer Engagement", framework:"LISTEN", domain:"customer-market",
      glyph:"❤", status:"active", now:"Triaging 4 tickets · NPS 61",
      identity:"The customer's voice inside the system. Handles support, runs user research, tracks NPS, and surfaces patterns that Strategos and Forge need to hear.",
      tools:["intercom","typeform","calendly","dovetail","posthog"],
      triggers:["customer feedback","support","NPS","user research","@ambassador"],
      escalates:["strategos","prime","agent-k"],
      perms:{ read:["support-tickets","nps-responses","user-events"], write:["support-replies","research-notes"], execute:["send-survey"] } },
  ];

  // ---- Coordination patterns (from the integration matrix) ----
  const PATTERNS = [
    { id:"A", title:"Code change · full quality gates", tone:"accent",
      trigger:"Implement the new saved-views feature",
      chain:["conductor","forge","atlas","inspector","guardian","pipeline","watchtower"],
      steps:[
        ["conductor","forge","Breakdown ready — ADR-036 → implement saved-views"],
        ["forge","atlas","Need a `saved_view` table + RLS for owner scoping"],
        ["atlas","forge","Schema + migration 0043 staged, RLS owner-only"],
        ["forge","inspector","PR #2244 up — 6 files, +210 −18"],
        ["inspector","guardian","Coverage 91%, e2e green — handing for sec review"],
        ["guardian","pipeline","No vulns, secrets clean — approved to ship"],
        ["pipeline","watchtower","Deployed canary 10% → 100%, post-deploy baseline?"],
        ["watchtower","tessa","SLOs steady, p95 +3ms. Feature live. ✓"],
      ] },
    { id:"B", title:"Incident response", tone:"rose",
      trigger:"P1 — checkout error rate spiking to 7%",
      chain:["watchtower","agent-k","guardian","pipeline","archivist","forge","inspector"],
      steps:[
        ["watchtower","agent-k","SLO breach: checkout 5xx at 7%, paging now"],
        ["agent-k","pipeline","Rolling back web@prod to last green build"],
        ["pipeline","agent-k","Rollback complete — error rate falling, 7% → 0.4%"],
        ["agent-k","guardian","Confirm not a security event before all-clear"],
        ["guardian","agent-k","No intrusion — bad deploy, regression in pricing svc"],
        ["agent-k","archivist","Stand down. Open post-mortem PM-0091"],
        ["archivist","forge","Root cause: null tax rate. Fix + regression test"],
        ["forge","inspector","Hotfix PR #2245 with covering test — please gate"],
      ] },
    { id:"C", title:"Customer-driven feature", tone:"teal",
      trigger:"Customers keep asking for bulk CSV export",
      chain:["ambassador","strategos","conductor","tessa","forge","validator","ambassador"],
      steps:[
        ["ambassador","strategos","Top NPS theme this month: bulk export (31 mentions)"],
        ["strategos","conductor","Prioritized for Q3 — fits 'reduce churn' OKR"],
        ["conductor","tessa","ADR-039 done. Route the build, flag-gated rollout"],
        ["tessa","forge","Implement export behind `bulk_export` flag"],
        ["forge","validator","Built + flagged. Want a staged rollout experiment?"],
        ["validator","ambassador","Live to 20%. Export-users retain +6pp — shipping wide"],
        ["ambassador","tessa","Closed the loop with 31 requesters. ✓"],
      ] },
    { id:"D", title:"Compliance-driven change", tone:"warm",
      trigger:"EU AI Act — classify & gate the AI summarizer",
      chain:["prime","conductor","atlas","guardian","forge","inspector","pipeline"],
      steps:[
        ["prime","conductor","EU AI Act: summarizer is limited-risk, needs disclosure + logging"],
        ["conductor","atlas","Need an `ai_disclosure_log` retained 12 months"],
        ["atlas","guardian","Log table + RLS staged — audit the access policy"],
        ["guardian","forge","RLS sound. Add disclosure banner + log write path"],
        ["forge","inspector","PR #2246 — disclosure UI + logging, please gate"],
        ["inspector","pipeline","Tests green, evidence captured for Prime"],
        ["pipeline","prime","Shipped. Evidence filed to Vanta control AI-1.2 ✓"],
      ] },
    { id:"E", title:"AI feature launch", tone:"acid",
      trigger:"Launch the AI reply-suggestions feature",
      chain:["conductor","ethica","forge","inspector","guardian","pipeline","watchtower","validator"],
      steps:[
        ["conductor","ethica","ADR-040 ready — review reply-suggestions for risk tier"],
        ["ethica","forge","Limited-risk. Require moderation + opt-out + bias audit"],
        ["forge","inspector","Built with moderation hook + opt-out. Gate please"],
        ["inspector","guardian","Coverage 88%, prompt-injection tests added"],
        ["guardian","pipeline","No data leak paths — approved behind flag"],
        ["pipeline","watchtower","Canary 5%. Watch token cost + latency"],
        ["watchtower","validator","Latency p95 +40ms (ok). Measure acceptance rate"],
        ["validator","ethica","27% accept, no bias flags. Ramp to 100% ✓"],
      ] },
  ];

  // ---- Ambient feed templates (random inter-agent chatter) ----
  const CHATTER = [
    ["watchtower","tessa","p95 latency steady at 218ms across regions"],
    ["forge","inspector","Pushed fix for flaky login test — re-run?"],
    ["atlas","guardian","RLS policy updated on `event_log`, please re-audit"],
    ["ambassador","strategos","NPS ticked to 61 (+2) week-over-week"],
    ["validator","strategos","exp-checkout-v3 reached 94% confidence"],
    ["prime","conductor","Access review due in 9 days for CC6.1"],
    ["guardian","forge","Snyk: 1 moderate dep advisory in `undici`"],
    ["inspector","pipeline","Coverage held at 91% on main"],
    ["archivist","conductor","ADR-037 archived, linked from pattern library"],
    ["pipeline","watchtower","web@prod deploy 8f2c1 healthy, baseline captured"],
    ["ethica","prime","Quarterly bias audit scheduled for the summarizer"],
    ["sentinel","conductor","No prompt drift detected in last agent diff"],
    ["strategos","tessa","Reprioritized backlog — export moves up to P1"],
    ["tessa","forge","Routing issue FF-1182 your way, context attached"],
    ["watchtower","agent-k","Error budget 92% remaining this window"],
  ];

  const SCENARIOS = ["All systems nominal","2 deploys in flight","1 experiment ramping","0 open incidents"];

  // ---- Integration matrix (row → column): what the column agent does for the row agent ----
  const RELATIONS = {
    tessa: { "agent-k":"escalate P0", conductor:"request ADR", sentinel:"request agent review", forge:"route code task", pipeline:"coordinate deploy", atlas:"request schema", inspector:"request tests", guardian:"request sec review", prime:"request compliance check", ethica:"request AI review", watchtower:"check SLO health", validator:"plan experiment", strategos:"strategic input", archivist:"log workflow", ambassador:"user feedback in" },
    "agent-k": { tessa:"report incident", conductor:"post-incident ADR", sentinel:"post-incident agent review", forge:"hand fix to", pipeline:"trigger rollback", atlas:"emergency restore", inspector:"skip in emergency", guardian:"bypass with sign-off", prime:"defer with sign-off", ethica:"bypass with sign-off", watchtower:"confirm metrics", validator:"pause experiments", strategos:"report business impact", archivist:"post-mortem", ambassador:"user comms" },
    conductor: { tessa:"hand off ADR", sentinel:"request agent review", forge:"implementation breakdown", pipeline:"deploy strategy", atlas:"data model", inspector:"test strategy", guardian:"sec implications", prime:"compliance impact", ethica:"AI risk tier", watchtower:"SLO targets", validator:"experiment design", strategos:"OKR alignment", archivist:"ADR archive" },
    sentinel: { conductor:"escalate spec issue", forge:"code change review", pipeline:"deploy of agent file", inspector:"spec test", guardian:"sec audit", prime:"compliance audit", ethica:"AI policy review", archivist:"changelog" },
    forge: { tessa:"report completion", conductor:"request ADR clarity", sentinel:"spec review", pipeline:"submit PR for deploy", atlas:"request schema", inspector:"submit for test", guardian:"submit for review", ethica:"submit AI feature", watchtower:"perf check", validator:"implement flag", archivist:"document patterns" },
    pipeline: { tessa:"report deploy", "agent-k":"trigger if blocks", forge:"deploy code", atlas:"run migrations", inspector:"run tests", guardian:"scan results", watchtower:"post-deploy SLO", validator:"feature rollout", archivist:"deploy log" },
    atlas: { tessa:"schema ready", "agent-k":"emergency restore", conductor:"data implications", forge:"provide schema", pipeline:"migration script", inspector:"query tests", guardian:"RLS audit", prime:"data privacy", watchtower:"query perf", archivist:"doc schema" },
    inspector: { tessa:"test results", "agent-k":"skip in P0", forge:"test feedback", pipeline:"gate result", atlas:"test queries", guardian:"sec tests", prime:"compliance tests", ethica:"AI bias tests", watchtower:"perf tests", validator:"experiment validation", archivist:"flaky-test patterns" },
    guardian: { tessa:"sec status", "agent-k":"active threat", conductor:"sec architecture", forge:"approve PR", pipeline:"block deploy", atlas:"RLS audit", prime:"sec controls", ethica:"AI safety", watchtower:"sec monitoring", archivist:"threat model" },
    prime: { tessa:"compliance status", conductor:"compliance impact", atlas:"data privacy", inspector:"compliance tests", guardian:"implement controls", ethica:"AI governance", watchtower:"compliance metrics", archivist:"policy archive", ambassador:"privacy req handling" },
    ethica: { tessa:"AI status", conductor:"AI architecture", forge:"AI approval", inspector:"AI tests", guardian:"AI security", prime:"AI governance", watchtower:"AI monitoring", validator:"AI experiment", archivist:"AI policy", ambassador:"user-reported AI issue" },
    watchtower: { tessa:"route alert", "agent-k":"page on SLO breach", forge:"regression alert", pipeline:"post-deploy baseline", atlas:"query perf", inspector:"perf tests", guardian:"sec monitoring", prime:"compliance monitoring", ethica:"AI monitoring", validator:"guardrail metrics", strategos:"OKR dashboard", ambassador:"outage alert" },
    validator: { tessa:"report decision", "agent-k":"pause on incident", forge:"implement experiment", pipeline:"feature flag", inspector:"experiment validation", ethica:"AI experiment review", watchtower:"guardrail check", strategos:"inform OKR", archivist:"experiment learning" },
    strategos: { tessa:"priority order", conductor:"strategic ADR", forge:"priority signal", watchtower:"OKR vs SLO", validator:"hypothesis to test", archivist:"OKR archive", ambassador:"customer priority" },
    archivist: { tessa:"surface prior art", conductor:"ADR collection", sentinel:"changelog source", forge:"pattern library", pipeline:"runbook archive", atlas:"schema docs", inspector:"flaky-test register", guardian:"threat model archive", prime:"policy archive", ethica:"AI policy archive", watchtower:"dashboard owners", validator:"experiment learnings", strategos:"OKR archive" },
    ambassador: { tessa:"customer themes", "agent-k":"customer-detected outage", conductor:"customer-driven ADR", forge:"bug repro", guardian:"sec report", prime:"privacy req", ethica:"AI complaint", watchtower:"outage from users", validator:"hypothesis source", strategos:"NPS / themes", archivist:"research notes" },
  };

  // ---- Incidents ----
  // sev: P0 | P1 | P2 | P3 · status: active | monitoring | resolved
  const INCIDENTS = [
    { id:"INC-0093", sev:"P2", status:"active", title:"Search relevance degraded after index rebuild",
      opened:"Jun 4 · 09:48", age:"running 41m", lead:"watchtower",
      agents:["watchtower","tessa","atlas","forge","inspector"],
      impact:"Top-result click-through down ~14% since 09:07. No errors — results are simply worse.",
      cause:"Under investigation — suspected stale embedding cache after the 09:00 reindex job.",
      timeline:[
        ["watchtower","tessa","Guardrail tripped: search CTR −14% vs 7-day baseline"],
        ["tessa","atlas","Reindex job 09:00 is the prime suspect — check embeddings"],
        ["atlas","forge","Embedding cache served stale vectors for ~30% of queries"],
        ["forge","inspector","Cache-bust patch ready (PR #2249) — validating relevance",,"running"],
      ] },
    { id:"INC-0091", sev:"P1", status:"resolved", title:"Checkout 5xx error-rate spike",
      opened:"Jun 3 · 14:22", age:"resolved in 18m", lead:"agent-k", patternRef:"B",
      agents:["watchtower","agent-k","pipeline","guardian","archivist","forge","inspector"],
      impact:"~3.2% of checkout sessions errored for 18 minutes. No data loss, no charges affected.",
      cause:"Null tax rate for a newly-added region in the pricing service, shipped in deploy 8e1a4f.",
      timeline:[
        ["watchtower","agent-k","SLO breach: checkout 5xx at 7%, paging now"],
        ["agent-k","pipeline","Rolling back web@prod to last green build"],
        ["pipeline","agent-k","Rollback complete — error rate 7% → 0.4%"],
        ["agent-k","guardian","Confirm this isn't a security event before all-clear"],
        ["guardian","agent-k","No intrusion — bad deploy, pricing-svc regression"],
        ["agent-k","archivist","Stand down. Opening post-mortem PM-0091"],
        ["forge","inspector","Hotfix PR #2245 + covering test for null tax rate"],
      ] },
    { id:"INC-0090", sev:"P0", status:"resolved", title:"Auth provider outage — logins failing globally",
      opened:"Jun 1 · 02:11", age:"resolved in 34m", lead:"agent-k",
      agents:["watchtower","agent-k","guardian","ambassador","archivist","conductor"],
      impact:"New logins failed for 34 min overnight. Existing sessions stayed valid; ~1,100 users affected.",
      cause:"Upstream identity provider regional outage. No fault on our side; failover was too slow.",
      timeline:[
        ["watchtower","agent-k","P0: login success rate 99% → 11%, upstream IdP 5xx"],
        ["agent-k","guardian","Confirm not credential-stuffing before we widen access"],
        ["guardian","agent-k","Clean — it's the IdP. Safe to fail over to backup region"],
        ["agent-k","ambassador","Failover live. Post a status-page notice for users"],
        ["agent-k","conductor","Need an ADR: automate IdP failover, 34m is too slow"],
        ["conductor","archivist","ADR-041 drafted — archive PM-0090 with action items"],
      ] },
    { id:"INC-0088", sev:"P2", status:"resolved", title:"Elevated p95 latency in EU region",
      opened:"May 28 · 16:40", age:"resolved in 1h 12m", lead:"watchtower",
      agents:["watchtower","atlas","forge","pipeline"],
      impact:"EU p95 latency climbed to 880ms for ~1h. Slow, not broken — no errors raised.",
      cause:"A missing index on event_log made a hot query do sequential scans under EU peak load.",
      timeline:[
        ["watchtower","atlas","EU p95 at 880ms — DB CPU pinned, slow query on event_log"],
        ["atlas","forge","Adding composite index (tenant_id, created_at) — migration 0041"],
        ["forge","pipeline","Migration reviewed — ship to EU primary off-peak"],
        ["pipeline","watchtower","Index live. p95 back to 210ms, CPU normal ✓"],
      ] },
    { id:"INC-0085", sev:"P3", status:"resolved", title:"Flaky e2e test blocking the deploy queue",
      opened:"May 24 · 11:05", age:"resolved in 2h 30m", lead:"inspector",
      agents:["inspector","forge","pipeline","archivist"],
      impact:"No customer impact — a flaky login test intermittently red-lit CI and stalled 3 merges.",
      cause:"Race condition in the test's session setup, not the app. Fixed with an explicit wait.",
      timeline:[
        ["inspector","forge","login.e2e flaky — fails ~1 in 4, blocking the merge queue"],
        ["forge","inspector","Race in session setup — added explicit await on auth cookie"],
        ["inspector","pipeline","Stable across 40 reruns — unblocking the queue"],
        ["inspector","archivist","Logged to the flaky-test register with the root cause"],
      ] },
  ];

  return { DOMAINS, AGENTS, PATTERNS, CHATTER, SCENARIOS, RELATIONS, INCIDENTS };
})();
