// Capability Map data — extracted verbatim from capability-map.jsx
// CATS: capability categories. CONNECTIONS: compound patterns.
window.CAP_DATA = {
  CATS: [
  { id:"icons", label:"Icons & Graphics", emoji:"🎨", items:[
    { name:"Lucide React",      avail:"bundled", desc:"1500+ icons, import in React",
      label:"lucide-react",
      prompt:"import { Settings, User, Bell, Search, ChevronRight, X, Plus, Trash2, Edit2, Download } from 'lucide-react' — render with size={20} or className='w-5 h-5' and a text-color class",
      demo:"Grid of 20 lucide-react icons showing different sizes, colors, and stroke widths" },
    { name:"Tabler Icons",      avail:"bundled", desc:"5800+ icons via font in SVG widgets",
      label:"tabler icons",
      prompt:"In SVG widgets: <i class='ti ti-settings'></i> — sized via font-size, colored via color. Never use -filled suffixes. Outline only.",
    },
    { name:"Solar Icons",       avail:"manual",  desc:"Duotone/broken — most distinctive available",
      label:"Solar duotone SVG",
      prompt:"Get SVG path data from iconify.design/solar — embed as inline SVG with two <path> elements: first at opacity:1 for the base, second at opacity:0.3-0.5 for the duotone layer. Both paths share the same viewBox.",
      demo:"12 Solar duotone icons in a styled card grid, showing the two-tone effect" },
    { name:"Phosphor Icons",    avail:"cdn",     desc:"6 weights including duotone",
      label:"Phosphor (unpkg)",
      prompt:"<script src='https://unpkg.com/@phosphor-icons/web'></script> — <i class='ph-duotone ph-gear'></i> — weights: ph-thin ph-light ph ph-bold ph-fill ph-duotone. Size via font-size CSS.",
      demo:"Same icon in all 6 Phosphor weights side by side" },
    { name:"Hugeicons",         avail:"manual",  desc:"3600+ premium icons, multiple styles",
      label:"Hugeicons SVG",
      prompt:"Get SVG paths from hugeicons.com — copy the stroke-based SVG, embed inline. Adjust stroke-width for visual weight. These have distinct rounded corners that read as premium.",
    },
    { name:"Mingcute",          avail:"cdn",     desc:"Rounded, warm — distinctly non-generic",
      label:"Mingcute CDN",
      prompt:"<link rel='stylesheet' href='https://cdn.jsdelivr.net/npm/@mingcute/icon-web@latest/dist/all.css'> — <i class='mgc_settings_line'></i> or mgc_settings_fill. Warm, rounded, unmistakably not Lucide.",
    },
    { name:"Simple Icons",      avail:"cdn",     desc:"3000+ brand logos only",
      label:"Simple Icons brands",
      prompt:"<script src='https://cdn.jsdelivr.net/npm/simple-icons@v11/index.min.js'></script> — use SVG path data from simpleicons.org. Each icon is a single monochrome path with the brand's official hex color.",
      demo:"Brand logo grid: GitHub, Vercel, Supabase, Stripe, Anthropic etc using Simple Icons" },
    { name:"Lordicon",          avail:"cdn",     desc:"Animated Lottie-based icon packs",
      label:"Lordicon animated",
      prompt:"<script src='https://cdn.lordicon.com/lordicon.js'></script> — <lord-icon src='https://cdn.lordicon.com/ICON_ID.json' trigger='hover' colors='primary:#6366f1,secondary:#a5b4fc' style='width:48px;height:48px'></lord-icon>",
      demo:"4 Lordicon animated icons with hover triggers and custom colors" },
  ]},
  { id:"type", label:"Typography", emoji:"✏️", items:[
    { name:"Google Fonts",        avail:"cdn",    desc:"Any font, fresh per artifact",
      label:"Google Fonts import",
      prompt:"<link href='https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600&display=swap' rel='stylesheet'> then font-family: 'Inter', system-ui, sans-serif on root. Or @import url() in <style>.",
      demo:"Load Geist, Playfair Display, and Space Grotesk — show each at multiple weights with sample text" },
    { name:"Variable Fonts",      avail:"cdn",    desc:"One file, adjustable weight/width/slant",
      label:"variable font + slider",
      prompt:"Load a variable font (e.g. Geist Mono or Fraunces) from Google Fonts with wght axis. Control with: el.style.fontVariationSettings = `'wght' ${value}`. Range: 100–900.",
      demo:"Slider that animates font-weight from 100 to 900 live on a large headline" },
    { name:"Fluid Typography",    avail:"builtin",desc:"Size scales with viewport via clamp()",
      label:"clamp() fluid type",
      prompt:"font-size: clamp(1rem, 2.5vw + 0.5rem, 1.5rem) — args are (min, preferred, max). For a scale: h1: clamp(2rem, 5vw + 1rem, 4rem), h2: clamp(1.5rem, 3vw + 0.75rem, 2.5rem).",
      demo:"Fluid type scale demo — drag to resize and see type scale in action" },
    { name:"Modular Type Scale",  avail:"builtin",desc:"Mathematically harmonious heading sizes",
      label:"1.25 type scale",
      prompt:"Base 1rem (16px), scale 1.25. xs:0.64rem sm:0.8rem base:1rem md:1.25rem lg:1.563rem xl:1.953rem 2xl:2.441rem 3xl:3.052rem. Apply via CSS custom properties: --text-lg: 1.563rem.",
    },
    { name:"Font Pairing",        avail:"builtin",desc:"Complementary display + body combos",
      label:"font pairing ask",
      prompt:"Recommend a high-contrast font pairing for [aesthetic]: one display/heading font and one body/UI font, with weights, sizes, and letter-spacing recommendations. Include the Google Fonts @import URLs.",
      demo:"4 curated font pairings with heading and body sample text for each" },
  ]},
  { id:"motion", label:"Animations & Motion", emoji:"⚡", items:[
    { name:"CSS Keyframes",        avail:"builtin",desc:"@keyframes on any CSS property",
      label:"@keyframes",
      prompt:"@keyframes fadeInUp { from { opacity:0; transform:translateY(16px) } to { opacity:1; transform:translateY(0) } } — apply: animation: fadeInUp 300ms ease-out forwards. Combine with animation-delay for stagger.",
    },
    { name:"Staggered Entrance",   avail:"builtin",desc:"Items cascade in with delay",
      label:"stagger on mount",
      prompt:"Each item: initial state opacity:0 translateY(12px). On mount, add 'visible' class or use inline transition-delay: index * 60ms. Transition: opacity 280ms ease-out, transform 280ms ease-out. Total offset capped at ~600ms.",
      demo:"8 cards stagger-animate in on load with delay cascade" },
    { name:"Scroll-Triggered",     avail:"builtin",desc:"IntersectionObserver on scroll",
      label:"IntersectionObserver",
      prompt:"const io = new IntersectionObserver(entries => entries.forEach(e => e.isIntersecting && e.target.classList.add('visible')), { threshold:0.15 }). CSS: .item { opacity:0; transform:translateY(20px); transition:opacity 400ms, transform 400ms } .item.visible { opacity:1; transform:none }",
      demo:"Sections animate in as you scroll down the page" },
    { name:"Counting Numbers",     avail:"builtin",desc:"Stats count from 0 on load",
      label:"count-up animation",
      prompt:"RAF loop: const animate = (start, end, duration) => { const startTime = performance.now(); const step = (now) => { const t = Math.min((now-startTime)/duration,1); const ease = t*(2-t); el.textContent = Math.round(start + (end-start)*ease); if(t<1) requestAnimationFrame(step) }; requestAnimationFrame(step) }",
      demo:"4 stat cards counting up from 0 to target values with easing" },
    { name:"Typewriter Effect",    avail:"builtin",desc:"Text types character by character",
      label:"typewriter + cursor",
      prompt:"Cycle phrases[]: type each char via setInterval(75ms), hold 1.8s at full, delete via setInterval(35ms), 400ms gap then next phrase. Blinking cursor: span with @keyframes blink { 0%,100%{opacity:1} 50%{opacity:0} } 800ms step-end infinite.",
      demo:"Typewriter cycling through 4 phrases with blinking cursor" },
    { name:"Micro-interactions",   avail:"builtin",desc:"Button press, hover, input feedback",
      label:"micro-interaction kit",
      prompt:"Buttons: active:scale(0.96) transition 100ms. Hover: subtle bg shift. Inputs: focus border-color transition 150ms + ring. Toggles: cubic-bezier(0.34,1.56,0.64,1) thumb spring. Rule: every interactive element has a visual response, max 200ms.",
      demo:"Micro-interaction kit — buttons, inputs, toggles with satisfying feedback" },
    { name:"Spring Physics",       avail:"builtin",desc:"Bouncy natural easing",
      label:"spring cubic-bezier",
      prompt:"CSS spring: transition: transform 400ms cubic-bezier(0.34,1.56,0.64,1) — natural overshoot. For JS: spring pos formula: x += velocity; velocity += (target-x)*stiffness; velocity *= (1-damping); where stiffness≈0.08 damping≈0.75.",
      demo:"Cards that snap to position with spring overshoot on drag release" },
    { name:"Canvas RAF Loop",      avail:"builtin",desc:"requestAnimationFrame animation",
      label:"RAF animation loop",
      prompt:"const canvas=document.querySelector('canvas'); const ctx=canvas.getContext('2d'); let state={}; const draw=()=>{ ctx.clearRect(0,0,W,H); update(state); render(ctx,state); requestAnimationFrame(draw) }; requestAnimationFrame(draw)",
    },
    { name:"GSAP",                 avail:"cdn",    desc:"Professional timeline animation",
      label:"GSAP from cdnjs",
      prompt:"<script src='https://cdnjs.cloudflare.com/ajax/libs/gsap/3.12.5/gsap.min.js'></script> — gsap.timeline().from('.card', { opacity:0, y:30, stagger:0.08, duration:0.5, ease:'power2.out' }).from('.heading', { opacity:0, scale:0.95, duration:0.4 }, '-=0.3')",
      demo:"GSAP timeline demo — load from cdnjs, staggered entrance sequence" },
    { name:"Anime.js",             avail:"cdn",    desc:"Lightweight JS animation library",
      label:"Anime.js CDN",
      prompt:"<script src='https://cdnjs.cloudflare.com/ajax/libs/animejs/3.2.1/anime.min.js'></script> — anime({ targets:'.el', translateX:250, rotate:'1turn', backgroundColor:'#FFF', duration:800, easing:'easeInOutQuad', delay:anime.stagger(100) })",
      demo:"Anime.js demo — SVG path drawing animation" },
    { name:"Lottie Web",           avail:"cdn",    desc:"JSON vector animation playback",
      label:"Lottie CDN",
      prompt:"<script src='https://cdnjs.cloudflare.com/ajax/libs/bodymovin/5.12.2/lottie.min.js'></script> — lottie.loadAnimation({ container:el, renderer:'svg', loop:true, autoplay:true, path:'https://assets10.lottiefiles.com/packages/lf20_ANIMATION_ID.json' })",
      demo:"Lottie animation demo with a public animation" },
    { name:"Framer Motion",        avail:"unavailable",desc:"Not bundled. Use CSS keyframes instead." },
  ]},
  { id:"bg", label:"Background Effects", emoji:"🌊", items:[
    { name:"Animated Gradient",    avail:"builtin",desc:"Shifting CSS color animation",
      label:"animated gradient",
      prompt:"background: linear-gradient(135deg, #667eea, #764ba2, #f97316, #06b6d4); background-size:300% 300%; @keyframes gradShift { 0%{background-position:0% 50%} 50%{background-position:100% 50%} 100%{background-position:0% 50%} } animation: gradShift 8s ease infinite",
      demo:"Animated gradient background — slow cycling vivid colors" },
    { name:"Canvas Particles",     avail:"builtin",desc:"Floating connected particles",
      label:"canvas particle BG",
      prompt:"70 particles each {x,y,vx:rand(-0.4,0.4),vy:rand(-0.4,0.4),r:2}. RAF: clear, move+wrap edges, ctx.beginPath/arc each. For pairs where dist<120: ctx.strokeStyle=`rgba(255,255,255,${(1-dist/120)*0.12})`",
      demo:"80 connected floating particles on dark background" },
    { name:"Aurora Effect",        avail:"builtin",desc:"Flowing gradient mesh, Northern Lights",
      label:"aurora CSS animation",
      prompt:"3-4 absolutely-positioned divs behind content, each: border-radius:50%, filter:blur(80px), opacity:0.5, one of [#7c3aed,#0d9488,#4f46e5,#db2777]. @keyframes for translateX/Y 8-12s infinite alternate ease-in-out with different delays. Dark base #060614.",
      demo:"Aurora background — slow flowing northern lights animation" },
    { name:"Noise / Grain",        avail:"builtin",desc:"SVG feTurbulence film grain",
      label:"SVG noise overlay",
      prompt:"<svg style='position:absolute;inset:0;width:100%;height:100%;pointer-events:none;opacity:0.04'><filter id='noise'><feTurbulence type='fractalNoise' baseFrequency='0.65' numOctaves='3' stitchTiles='stitch'/></filter><rect width='100%' height='100%' filter='url(#noise)'/></svg>",
      demo:"Film grain overlay on a clean card design" },
    { name:"CSS Dot / Grid",       avail:"builtin",desc:"Repeating CSS background pattern",
      label:"CSS dot pattern",
      prompt:"Dots: background-image:radial-gradient(circle, rgba(255,255,255,0.15) 1px, transparent 1px); background-size:24px 24px. Grid lines: background-image:linear-gradient(rgba(255,255,255,0.05) 1px,transparent 1px),linear-gradient(90deg,rgba(255,255,255,0.05) 1px,transparent 1px); background-size:40px 40px",
      demo:"4 different CSS background patterns side by side" },
    { name:"Floating Shapes",      avail:"builtin",desc:"Animated drifting geometric shapes",
      label:"floating shapes BG",
      prompt:"Absolutely-positioned divs: each a circle or square with random size 40-120px, color from palette, opacity 0.15-0.3. @keyframes float-N { 0%{transform:translate(0,0) rotate(0)} 100%{transform:translate(Xpx,Ypx) rotate(360deg)} } 10-20s infinite linear, each unique.",
      demo:"Colorful geometric shapes drifting on dark background" },
    { name:"Star Field",           avail:"builtin",desc:"Canvas twinkling star field",
      label:"canvas star field",
      prompt:"150 stars each {x,y,r:rand(0.5,1.5),opacity:rand(0.3,1),twinkleSpeed:rand(0.5,2)}. RAF: each star opacity += Math.sin(Date.now()*speed)*0.01, clamp 0.3-1. Perspective depth: 3 layers at different speeds on scroll.",
      demo:"Star field with parallax depth and twinkling" },
    { name:"Parallax Scroll",      avail:"builtin",desc:"Depth layers at different speeds",
      label:"parallax layers",
      prompt:"3 absolutely-positioned layers. window.addEventListener('scroll',()=>{ const y=window.scrollY; layer1.style.transform=`translateY(${y*0.1}px)`; layer2.style.transform=`translateY(${y*0.3}px)`; layer3.style.transform=`translateY(${y*0.6}px)` }) — wrap in requestAnimationFrame.",
      demo:"3 depth layers moving at different scroll speeds" },
    { name:"CSS Mesh Gradient",    avail:"builtin",desc:"Multi-point color mesh",
      label:"CSS mesh gradient",
      prompt:"background: radial-gradient(at 40% 20%, #7c3aed 0px, transparent 50%), radial-gradient(at 80% 0%, #3b82f6 0px, transparent 50%), radial-gradient(at 0% 50%, #ec4899 0px, transparent 50%), radial-gradient(at 80% 50%, #10b981 0px, transparent 50%), radial-gradient(at 0% 100%, #f59e0b 0px, transparent 50%)",
      demo:"Rich multi-point CSS mesh gradient" },
    { name:"Morphing Blobs",       avail:"builtin",desc:"Organic SVG shapes that morph",
      label:"morphing SVG blobs",
      prompt:"SVG path with <animate attributeName='d' values='M60,20C80,5 95,5 110,20C125,35 130,60 110,75C90,90 70,90 55,75C35,60 35,35 60,20Z; M55,15C80,0 100,10 115,30C130,50 125,75 105,85C80,95 55,90 40,70C25,50 30,30 55,15Z; ...' dur='8s' repeatCount='indefinite'/>",
      demo:"Morphing SVG blob background — organic shapes shifting" },
    { name:"Three.js 3D BG",       avail:"bundled",desc:"Full 3D scene background, React only",
      label:"Three.js r128 BG",
      prompt:"import * as THREE from 'three' — const renderer=new THREE.WebGLRenderer({alpha:true}), scene, camera=new THREE.PerspectiveCamera(75,w/h,0.1,1000). Add ambient+point lights, mesh, requestAnimationFrame loop with mesh.rotation.x/y += 0.003.",
      demo:"Three.js background — rotating geometry, dark scene" },
  ]},
  { id:"fx", label:"Visual Effects", emoji:"✨", items:[
    { name:"Glassmorphism",        avail:"builtin",desc:"backdrop-filter blur + transparency",
      label:"glassmorphism CSS",
      prompt:"background:rgba(255,255,255,0.07); backdrop-filter:blur(20px) saturate(180%); -webkit-backdrop-filter:blur(20px) saturate(180%); border:1px solid rgba(255,255,255,0.12); box-shadow:0 8px 32px rgba(0,0,0,0.25). Dark bg behind for effect to be visible.",
      demo:"Frosted glass cards floating over vivid blurred shapes" },
    { name:"Neumorphism",          avail:"builtin",desc:"Soft extruded plastic look",
      label:"neumorphism shadows",
      prompt:"background: #e0e5ec (light) or #2d3436 (dark). Raised: box-shadow: 6px 6px 12px rgba(0,0,0,0.15), -6px -6px 12px rgba(255,255,255,0.7). Inset (pressed): box-shadow: inset 4px 4px 8px rgba(0,0,0,0.15), inset -4px -4px 8px rgba(255,255,255,0.7). Match bg exactly.",
      demo:"Neumorphic UI components on matching soft background" },
    { name:"Gradient Text",        avail:"builtin",desc:"CSS background-clip on text",
      label:"gradient text CSS",
      prompt:"background:linear-gradient(135deg, #6366f1 0%, #8b5cf6 50%, #ec4899 100%); -webkit-background-clip:text; -webkit-text-fill-color:transparent; background-clip:text; display:inline-block. Works on any font weight.",
      demo:"Large headlines with vivid gradient fills, multiple directions" },
    { name:"Glow / Bloom",         avail:"builtin",desc:"box-shadow glow layers",
      label:"multi-layer glow",
      prompt:"box-shadow: 0 0 10px rgba(99,102,241,0.4), 0 0 30px rgba(99,102,241,0.2), 0 0 60px rgba(99,102,241,0.08). For text: text-shadow: 0 0 10px rgba(99,102,241,0.8), 0 0 30px rgba(99,102,241,0.4). Animate intensity with CSS variables.",
      demo:"Glowing elements and buttons on dark background" },
    { name:"clip-path Masking",    avail:"builtin",desc:"Diagonal cuts, polygon masks",
      label:"clip-path shapes",
      prompt:"Diagonal cut: clip-path:polygon(0 0, 100% 0, 100% 85%, 0 100%). Circle: clip-path:circle(50%). Custom: clip-path:polygon(0 0, 70% 0, 100% 100%, 0 100%). Animate between shapes: transition:clip-path 400ms ease-in-out.",
      demo:"Diagonal cuts, polygon masks, animated clip-path transitions" },
    { name:"mix-blend-mode",       avail:"builtin",desc:"Photoshop-style layer blending",
      label:"mix-blend-mode",
      prompt:"On overlapping element: mix-blend-mode:multiply (darken), screen (lighten), overlay (contrast), color-dodge (vivid), difference (invert). Combine with opacity. Requires non-white/black backgrounds to see effect.",
      demo:"Text and shapes with different blend modes over an image" },
    { name:"SVG Filters",          avail:"builtin",desc:"feTurbulence, feDisplacementMap",
      label:"SVG filter effects",
      prompt:"Liquid distortion: <filter id='distort'><feTurbulence type='turbulence' baseFrequency='0.02' numOctaves='3' seed='2'/><feDisplacementMap in='SourceGraphic' scale='20'/></filter>. Glow: <feGaussianBlur stdDeviation='4'/><feComposite operator='over' in2='SourceGraphic'/>",
      demo:"SVG filter demo — turbulence distortion, liquid glass effect" },
    { name:"Holographic",          avail:"builtin",desc:"Hue-rotating gradient, foil feel",
      label:"iridescent foil CSS",
      prompt:"background:linear-gradient(45deg,#ff0080,#7928ca,#0070f3,#00dfd8,#ff0080); background-size:200% 200%; animation:holo 3s linear infinite; @keyframes holo{to{background-position:200% 0}} — combine with mix-blend-mode:overlay for subtlety.",
      demo:"Holographic iridescent card — foil-like shifting colors on hover" },
    { name:"3D Tilt on Hover",     avail:"builtin",desc:"CSS perspective tilt on mouse",
      label:"CSS 3D tilt hover",
      prompt:"onMouseMove: const {left,top,width,height}=el.getBoundingClientRect(); const x=(e.clientX-left)/width-0.5; const y=(e.clientY-top)/height-0.5; el.style.transform=`perspective(600px) rotateY(${x*20}deg) rotateX(${-y*20}deg) scale(1.02)`. Reset on mouseleave.",
      demo:"Cards that tilt toward mouse cursor with perspective depth" },
    { name:"Bento Grid",           avail:"builtin",desc:"Asymmetric spanning card grid",
      label:"CSS bento grid",
      prompt:"display:grid; grid-template-columns:repeat(4,1fr); gap:12px. Featured card: grid-column:span 2; grid-row:span 2. Wide card: grid-column:span 3. Use grid-template-areas or span integers to control layout. Min card height 160px.",
      demo:"Bento grid — asymmetric spanning cards like Vercel's homepage" },
    { name:"Brutalist",            avail:"builtin",desc:"Bold borders, raw type, high contrast",
      label:"brutalist style",
      prompt:"Heavy borders: border:3px solid #000. Raw type: font-family:monospace or impact. No border-radius or border-radius:0. High contrast: black/white/one accent. Offset shadows: box-shadow:4px 4px 0 #000. Visible structure, no decoration.",
      demo:"Brutalist design — heavy borders, raw type, stark contrast" },
  ]},
  { id:"comp", label:"Components", emoji:"🧩", items:[
    { name:"shadcn/ui",            avail:"bundled",desc:"Alert, Button, Card, Dialog, Tabs…",
      label:"shadcn/ui import",
      prompt:"import { Button } from '@/components/ui/button' — import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card' — import { Badge } from '@/components/ui/badge' — import { Tabs, TabsContent, TabsList, TabsTrigger } from '@/components/ui/tabs'",
      demo:"shadcn/ui showcase — cards, badges, buttons, tabs, dialogs" },
    { name:"Command Palette",      avail:"builtin",desc:"⌘K search overlay, keyboard nav",
      label:"⌘K command palette",
      prompt:"State: open (Cmd+K), query. Filter commands[{id,label,action}] by query. Render: fixed overlay, backdrop-blur, input at top, filtered list below. Arrow keys change selectedIdx, Enter calls action, Escape closes. Focus trap inside.",
      demo:"⌘K command palette with keyboard nav and sample commands" },
    { name:"Kanban Board",         avail:"builtin",desc:"Drag-and-drop columns",
      label:"kanban drag-drop",
      prompt:"Columns: [{id,title,cards:[]}]. HTML5 DnD: onDragStart store cardId+columnId, onDragOver preventDefault, onDrop move card between columns. Visual: dragging card opacity:0.4, drop zone highlight. State update: immutable splice/push.",
      demo:"Kanban — 3 columns, draggable cards, drop zones" },
    { name:"Data Table",           avail:"builtin",desc:"Sortable, filterable, paginated",
      label:"sort+filter table",
      prompt:"State: data[], sortKey, sortDir, filterQuery, page, pageSize=20. Filter: data.filter(row=>JSON.stringify(row).toLowerCase().includes(q)). Sort: [...filtered].sort((a,b)=>dir*(a[key]>b[key]?1:-1)). Paginate: slice((page-1)*pageSize, page*pageSize).",
      demo:"Data table — 50 rows, sortable columns, search, pagination" },
    { name:"Timeline",             avail:"builtin",desc:"Vertical event timeline",
      label:"vertical timeline",
      prompt:"Vertical line (left border on container). Each event: dot (absolute, circular), date, title, description. Alternating left/right or all-right layout. Animate each event with IntersectionObserver on scroll.",
      demo:"Vertical timeline with icons, dates, animated entrance" },
    { name:"Stepper / Wizard",     avail:"builtin",desc:"Multi-step flow with progress",
      label:"multi-step wizard",
      prompt:"Steps array with {id,label,valid()}. State: currentStep. Header: step indicators with completed/active/pending states. Content: render steps[currentStep].component. Nav: Back (disabled at 0), Next (disabled if !valid()), disabled until complete.",
      demo:"4-step wizard with animated progress and validation" },
    { name:"Toast Notifications",  avail:"builtin",desc:"Pop-up messages with queue",
      label:"toast queue system",
      prompt:"State: toasts:[{id,type,message,duration}]. addToast appends to array. Each toast: setTimeout to remove after duration. Render: fixed bottom-right, stacked with gap. Animate: slide-in from right, slide-out on dismiss. Types: success/error/warning/info.",
      demo:"Toast system — success, error, warning, info with auto-dismiss" },
    { name:"Circular Progress",    avail:"builtin",desc:"SVG ring indicator",
      label:"SVG progress ring",
      prompt:"SVG circle: cx=50 cy=50 r=45. stroke-dasharray=283 (2πr). stroke-dashoffset=283*(1-percent/100). Transition:stroke-dashoffset 600ms ease. strokeLinecap=round. Two circles: track (opacity 0.1) + progress. Text in center via foreignObject or absolute position.",
      demo:"Circular progress rings — multiple sizes and colors, animated" },
    { name:"Color Picker",         avail:"builtin",desc:"Interactive HSL selector",
      label:"HSL color picker",
      prompt:"3 range inputs: hue 0-360, saturation 0-100, lightness 0-100. Live preview box: background:hsl(h,s%,l%). Output hex via hslToHex() function. Optionally: 2D canvas gradient for saturation/lightness, 1D bar for hue.",
      demo:"Interactive HSL color picker with live preview and hex output" },
    { name:"File Upload Zone",     avail:"builtin",desc:"Drag-and-drop file uploader",
      label:"drag-drop upload zone",
      prompt:"onDragOver:preventDefault+setDragOver(true), onDragleave:setDragOver(false), onDrop:e.dataTransfer.files. Also <input type=file accept='.pdf,.csv,.jpg'>. Show file name, size, type icon after selection. Validate type/size before accepting.",
      demo:"File upload zone — drag and drop with type validation and preview" },
    { name:"Virtual List",         avail:"builtin",desc:"Render thousands of rows",
      label:"virtual scroll list",
      prompt:"Container: overflow-y:scroll, fixed height. State: scrollTop. visibleStart=Math.floor(scrollTop/itemHeight), visibleEnd=visibleStart+Math.ceil(containerH/itemHeight)+1. Render only items[visibleStart..visibleEnd] with paddingTop=visibleStart*itemHeight.",
      demo:"Virtualized list — 10,000 rows, smooth scroll, no lag" },
    { name:"Rich Accordion",       avail:"builtin",desc:"Animated expand/collapse",
      label:"animated accordion",
      prompt:"State: openIndex. Content height animation: max-height:0→max-height:500px transition 300ms ease, overflow:hidden. Or use CSS grid-template-rows:0fr→1fr. Rotate chevron: transform:rotate(0)→rotate(180deg) on open.",
      demo:"Accordion with smooth height animation and rotating icons" },
  ]},
  { id:"threed", label:"3D & Canvas", emoji:"🎲", items:[
    { name:"Three.js r128",        avail:"bundled",desc:"Scenes, meshes, lighting, cameras",
      label:"Three.js r128",
      prompt:"import * as THREE from 'three' — const scene=new THREE.Scene(); const camera=new THREE.PerspectiveCamera(75,W/H,0.1,1000); const renderer=new THREE.WebGLRenderer({antialias:true,alpha:true}); scene.add(new THREE.AmbientLight(0xffffff,0.5)); mesh.rotation.x/y+=0.005 in RAF loop.",
      demo:"Three.js rotating icosahedron — emissive material, dark scene" },
    { name:"CSS 3D Card Flip",     avail:"builtin",desc:"Front/back card flip",
      label:"CSS 3D card flip",
      prompt:"Container: perspective:1000px. Card: transform-style:preserve-3d, transition:transform 600ms. .flipped: transform:rotateY(180deg). Front: backface-visibility:hidden. Back: transform:rotateY(180deg); backface-visibility:hidden. Same position absolute.",
      demo:"Click cards to reveal back face with 3D flip" },
    { name:"CSS 3D Depth",         avail:"builtin",desc:"Mouse parallax with perspective",
      label:"mouse parallax 3D",
      prompt:"onMouseMove on container: const x=(e.clientX/W-0.5)*20; const y=(e.clientY/H-0.5)*20. Layer 1: transform:translateZ(0px) — Layer 2: transform:translateZ(20px) — Layer 3: transform:translateZ(50px). Container: perspective:800px transform-style:preserve-3d.",
      demo:"Mouse-driven 3D parallax depth — layers separate on move" },
    { name:"HTML Canvas 2D",       avail:"builtin",desc:"Custom 2D canvas rendering",
      label:"canvas 2D API",
      prompt:"const canvas=document.querySelector('canvas'); const ctx=canvas.getContext('2d'); canvas.width=W; canvas.height=H. RAF loop: ctx.clearRect, ctx.fillStyle/strokeStyle, ctx.beginPath, ctx.arc/lineTo/rect, ctx.fill/stroke. Scale for retina: canvas.width=W*dpr; ctx.scale(dpr,dpr).",
      demo:"Canvas 2D generative art — animated geometric pattern" },
    { name:"WebGL / GLSL",         avail:"builtin",desc:"GPU fragment shaders",
      label:"WebGL GLSL shader",
      prompt:"const gl=canvas.getContext('webgl'). Compile vertex+fragment shaders, link program, draw fullscreen quad. Fragment shader receives u_time uniform. Pattern: vec2 uv=gl_FragCoord.xy/u_resolution; vec3 col=0.5+0.5*cos(u_time+uv.xyx+vec3(0,2,4)); gl_FragColor=vec4(col,1)",
      demo:"WebGL fragment shader — animated color pattern" },
  ]},
  { id:"viz", label:"Data Visualization", emoji:"📊", items:[
    { name:"recharts",             avail:"bundled",desc:"Line, Bar, Area, Pie, Radar, Treemap",
      label:"recharts chart",
      prompt:"import { ResponsiveContainer, LineChart, Line, XAxis, YAxis, CartesianGrid, Tooltip, Legend } from 'recharts'. <ResponsiveContainer width='100%' height={300}><LineChart data={data}><CartesianGrid strokeDasharray='3 3'/><XAxis dataKey='name'/><Line type='monotone' dataKey='value' stroke='#6366f1' strokeWidth={2}/></LineChart></ResponsiveContainer>",
      demo:"recharts showcase — 4 chart types with real-looking data" },
    { name:"d3",                   avail:"bundled",desc:"Force graphs, tree, custom SVG",
      label:"d3 force graph",
      prompt:"import * as d3 from 'd3'. const sim=d3.forceSimulation(nodes).force('link',d3.forceLink(links).id(d=>d.id)).force('charge',d3.forceManyBody().strength(-100)).force('center',d3.forceCenter(W/2,H/2)). On tick: update SVG line x1/y1/x2/y2 and circle cx/cy.",
      demo:"d3 force-directed graph — 25 connected labeled nodes" },
    { name:"plotly",               avail:"bundled",desc:"Scientific charts, 3D surfaces",
      label:"plotly 3D chart",
      prompt:"import * as Plotly from 'plotly'. Plotly.newPlot(el, [{type:'surface', z:zData, colorscale:'Viridis'}], {scene:{camera:{eye:{x:1.5,y:1.5,z:1}}},margin:{l:0,r:0,b:0,t:0},paper_bgcolor:'rgba(0,0,0,0)'}).",
      demo:"plotly 3D surface plot — rotating animated chart" },
    { name:"Chart.js",             avail:"bundled",desc:"Canvas-based animated charts",
      label:"Chart.js canvas",
      prompt:"import * as Chart from 'chart.js'. Chart.Chart.register(...Chart.registerables). new Chart.Chart(canvas, { type:'bar', data:{ labels, datasets:[{data, backgroundColor:'#6366f1', borderRadius:4}] }, options:{ animation:{duration:800}, plugins:{legend:{display:false}} } })",
      demo:"Chart.js animated bar chart with hover tooltips" },
    { name:"Force Graph",          avail:"bundled",desc:"d3-force network visualization",
      label:"network force graph",
      prompt:"d3.forceSimulation with forceLink, forceManyBody(-120), forceCenter. SVG: <line> for edges, <circle> for nodes, <text> for labels. Drag: d3.drag() on nodes updates fx/fy. Node color by group, edge opacity by weight.",
      demo:"Network graph — 30 nodes, labeled edges, draggable" },
    { name:"Live Updating Chart",  avail:"builtin",desc:"Real-time streaming data",
      label:"live updating chart",
      prompt:"setInterval(1000ms): push new dataPoint to array, slice to last 30. recharts LineChart re-renders on state change. Animate: isAnimationActive={false} on Line to prevent re-draw flash. Use useRef for data to avoid stale closure.",
      demo:"Live recharts line chart with simulated real-time data feed" },
    { name:"Custom SVG Chart",     avail:"builtin",desc:"Hand-rolled SVG, full control",
      label:"hand-rolled SVG chart",
      prompt:"Scale functions: xScale(i)=padding + i*(W-2*padding)/(n-1), yScale(v)=H-padding-(v-min)/(max-min)*(H-2*padding). Draw: <polyline points={data.map((v,i)=>`${xScale(i)},${yScale(v)}`).join(' ')} fill='none' stroke='#6366f1' strokeWidth={2}/>",
      demo:"Custom SVG chart with entrance animation and tooltip" },
  ]},
  { id:"agent", label:"Agentic Features", emoji:"🤖", items:[
    { name:"sendPrompt()",         avail:"builtin",desc:"Button sends a message to Claude",
      label:"sendPrompt(text)",
      prompt:"sendPrompt('Specific follow-up question or action') — call this from button onClick handlers to drive the conversation from inside the artifact. The text appears as if the user typed it.",
      demo:"Buttons that trigger specific Claude follow-ups from inside the artifact" },
    { name:"Claude API in Art.",   avail:"builtin",desc:"Fetch /v1/messages inside artifact",
      label:"fetch /v1/messages",
      prompt:"const res=await fetch('https://api.anthropic.com/v1/messages',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({model:'claude-sonnet-4-20250514',max_tokens:1000,messages:[{role:'user',content:prompt}]})}); const d=await res.json(); return d.content[0].text",
      demo:"AI-powered artifact — user asks a question, Claude API responds inline" },
    { name:"Streaming Responses",  avail:"builtin",desc:"Token-by-token Claude streaming",
      label:"SSE streaming fetch",
      prompt:"Same fetch but add stream:true to body. const reader=res.body.getReader(); const decoder=new TextDecoder(); while(true){ const {done,value}=await reader.read(); if(done)break; const chunk=decoder.decode(value); parse SSE lines: data: {\"type\":\"content_block_delta\",\"delta\":{\"text\":\"...\"}}",
      demo:"Streaming Claude chat — tokens appear in real time" },
    { name:"Multi-turn Chat",      avail:"builtin",desc:"Full conversation history state",
      label:"multi-turn history",
      prompt:"State: messages:[{role:'user'|'assistant',content:string}]. On send: append {role:'user',content:input} to messages, call API with full messages array, append {role:'assistant',content:response}. Never truncate history in state — only truncate in API call if needed.",
      demo:"Full multi-turn chat UI powered by Claude API inside artifact" },
    { name:"Persistent Storage",   avail:"builtin",desc:"window.storage — cross-session",
      label:"window.storage API",
      prompt:"Save: await window.storage.set('key', JSON.stringify(data)). Load: try { const r=await window.storage.get('key'); const data=JSON.parse(r.value) } catch(e){ /* key doesn't exist */ }. List: const {keys}=await window.storage.list('prefix:'). Delete: await window.storage.delete('key')",
      demo:"Persistent counter and notes that survive page refresh" },
    { name:"Shared Storage",       avail:"builtin",desc:"window.storage shared:true",
      label:"shared storage board",
      prompt:"Pass true as 3rd arg to all calls: await window.storage.set('board:userId', data, true). All users of this artifact see the same data. Use for leaderboards, collaborative state, shared configs. Last-write-wins.",
      demo:"Shared leaderboard using window.storage shared:true" },
    { name:"MCP in Artifact",      avail:"builtin",desc:"mcp_servers in embedded API call",
      label:"mcp_servers param",
      prompt:"Add mcp_servers to the fetch body: {..., mcp_servers:[{type:'url',url:'https://mcp.notion.com/mcp',name:'notion'}]}. Claude will use those MCPs during its response. Surfaces your connected MCPs as tools the embedded Claude can call.",
    },
    { name:"File → Claude",        avail:"builtin",desc:"FileReader → base64 → API",
      label:"file upload to Claude",
      prompt:"const reader=new FileReader(); reader.onload=async(e)=>{ const base64=e.target.result.split(',')[1]; const res=await fetch('/v1/messages',{body:JSON.stringify({messages:[{role:'user',content:[{type:'document',source:{type:'base64',media_type:'application/pdf',data:base64}},{type:'text',text:'Summarize this'}]}]})})}; reader.readAsDataURL(file)",
      demo:"Upload file artifact — image or PDF analyzed by Claude inline" },
  ]},
  { id:"pro", label:"Pro / Community Libraries", emoji:"🔥", items:[
    { name:"ECharts (Apache)",     avail:"cdn",    desc:"30+ chart types, GL/3D — recharts can't compete",
      label:"ECharts from CDN",
      prompt:"<script src='https://cdnjs.cloudflare.com/ajax/libs/echarts/5.4.3/echarts.min.js'></script> — const chart=echarts.init(document.getElementById('chart')); chart.setOption({series:[{type:'sankey'|'sunburst'|'graph'|'treemap',data:[...],links:[...]}]})",
      demo:"ECharts chart type that recharts cannot do — sankey, sunburst, or 3D" },
    { name:"ApexCharts",           avail:"cdn",    desc:"Beautiful animated charts",
      label:"ApexCharts CDN",
      prompt:"<script src='https://cdnjs.cloudflare.com/ajax/libs/apexcharts/3.45.1/apexcharts.min.js'></script> — new ApexCharts(el,{chart:{type:'area',height:300,animations:{enabled:true}},series:[{name:'Value',data:[...]}],fill:{type:'gradient',gradient:{shadeIntensity:1,opacityFrom:0.7,opacityTo:0.1}}})",
      demo:"ApexCharts animated area chart with gradient fill" },
    { name:"AG Grid Community",    avail:"cdn",    desc:"Enterprise data grid, free tier",
      label:"AG Grid Community",
      prompt:"<script src='https://cdn.jsdelivr.net/npm/ag-grid-community/dist/ag-grid-community.min.js'></script> — agGrid.createGrid(container,{columnDefs:[{field:'name',sortable:true,filter:true,resizable:true}],rowData:[...],defaultColDef:{flex:1},pagination:true,paginationPageSize:20})",
      demo:"AG Grid — 500 rows with sort, filter, column resize, pagination" },
    { name:"Monaco Editor",        avail:"cdn",    desc:"VS Code editor in the browser",
      label:"Monaco via jsdelivr",
      prompt:"<script src='https://cdn.jsdelivr.net/npm/monaco-editor@0.45.0/min/vs/loader.js'></script> — require.config({paths:{vs:'https://cdn.jsdelivr.net/npm/monaco-editor@0.45.0/min/vs'}}); require(['vs/editor/editor.main'],()=>{ monaco.editor.create(container,{value,language:'javascript',theme:'vs-dark',minimap:{enabled:false}}) })",
      demo:"Monaco VS Code editor embedded in artifact" },
    { name:"React Flow / XYFlow",  avail:"cdn",    desc:"Interactive node-based diagram editor",
      label:"React Flow CDN",
      prompt:"<script src='https://cdn.jsdelivr.net/npm/@xyflow/react@12/dist/umd/index.js'></script> — nodes:[{id:'1',position:{x:100,y:100},data:{label:'Node 1'}}], edges:[{id:'e1-2',source:'1',target:'2'}]. Handles user dragging, connecting, selecting.",
      demo:"React Flow — 6 connected nodes, drag to rearrange" },
    { name:"p5.js",                avail:"cdn",    desc:"Creative coding, generative art",
      label:"p5.js CDN",
      prompt:"<script src='https://cdnjs.cloudflare.com/ajax/libs/p5.js/1.9.0/p5.min.js'></script> — new p5(p=>{ p.setup=()=>p.createCanvas(W,H); p.draw=()=>{ p.background(0,10); p.translate(p.width/2,p.height/2); /* draw */ } }, containerEl)",
      demo:"p5.js generative art — animated geometric pattern" },
    { name:"Matter.js",            avail:"cdn",    desc:"2D physics — gravity, collisions",
      label:"Matter.js physics",
      prompt:"<script src='https://cdnjs.cloudflare.com/ajax/libs/matter-js/0.19.0/matter.min.js'></script> — const {Engine,Render,Bodies,World,Runner}=Matter; const engine=Engine.create(); World.add(engine.world,[Bodies.rectangle(W/2,H+25,W,50,{isStatic:true}), ...boxBodies]); Runner.run(engine)",
      demo:"Matter.js physics — boxes falling and colliding with gravity" },
    { name:"Pixi.js",              avail:"cdn",    desc:"High-performance 2D WebGL renderer",
      label:"Pixi.js CDN",
      prompt:"<script src='https://cdnjs.cloudflare.com/ajax/libs/pixi.js/7.3.2/pixi.min.js'></script> — const app=new PIXI.Application({width:W,height:H,backgroundColor:0x000000,antialias:true}); container.appendChild(app.view); app.ticker.add(delta=>{ /* update sprites */ })",
      demo:"Pixi.js 2D WebGL animation demo" },
    { name:"Cytoscape.js",         avail:"cdn",    desc:"Graph viz with auto layouts",
      label:"Cytoscape.js CDN",
      prompt:"<script src='https://cdnjs.cloudflare.com/ajax/libs/cytoscape/3.26.0/cytoscape.min.js'></script> — cytoscape({container:el, elements:[{data:{id:'a'}},{data:{id:'b'}},{data:{id:'ab',source:'a',target:'b'}}], layout:{name:'cose'}, style:[{selector:'node',style:{'background-color':'#6366f1','label':'data(id)'}}]})",
      demo:"Cytoscape network graph — 20 nodes with cose layout" },
    { name:"Swiper.js",            avail:"cdn",    desc:"Modern touch slider/carousel",
      label:"Swiper.js CDN",
      prompt:"<link rel='stylesheet' href='https://cdn.jsdelivr.net/npm/swiper@11/swiper-bundle.min.css'> <script src='https://cdn.jsdelivr.net/npm/swiper@11/swiper-bundle.min.js'></script> — new Swiper('.swiper',{slidesPerView:1,spaceBetween:20,navigation:true,pagination:{clickable:true},loop:true})",
      demo:"Swiper carousel — 5 slides, navigation, pagination" },
    { name:"Quill Editor",         avail:"cdn",    desc:"Rich text editor",
      label:"Quill CDN",
      prompt:"<link href='https://cdn.jsdelivr.net/npm/quill@2/dist/quill.snow.css' rel='stylesheet'><script src='https://cdn.jsdelivr.net/npm/quill@2/dist/quill.js'></script> — const quill=new Quill('#editor',{theme:'snow',modules:{toolbar:[[{header:[1,2,false]}],['bold','italic','underline'],['link','image'],['clean']]}})",
      demo:"Quill rich text editor with formatting toolbar" },
    { name:"Prism.js",             avail:"cdn",    desc:"Syntax highlighting",
      label:"Prism.js CDN",
      prompt:"<link href='https://cdnjs.cloudflare.com/ajax/libs/prism/1.29.0/themes/prism-tomorrow.min.css' rel='stylesheet'><script src='https://cdnjs.cloudflare.com/ajax/libs/prism/1.29.0/prism.min.js'></script> — <pre><code class='language-javascript'>your code here</code></pre> — Prism.highlightAll()",
      demo:"Prism.js code blocks with Tomorrow Night theme" },
    { name:"Floating UI",          avail:"cdn",    desc:"Smart tooltips, collision-aware",
      label:"Floating UI CDN",
      prompt:"Load @floating-ui/dom from jsdelivr CDN — computePosition(reference, floating, { middleware:[offset(8), flip(), shift({padding:8})] }).then(({x,y}) => Object.assign(floating.style, {left:x+'px', top:y+'px'})). Handles viewport collisions automatically.",
      demo:"Floating tooltips that avoid viewport edges" },
    { name:"DnD Kit",              avail:"cdn",    desc:"Drag and drop for React",
      label:"DnD Kit CDN",
      prompt:"Install dnd-kit/core + dnd-kit/sortable — wrap list in DndContext + SortableContext. Each item calls useSortable({id}), applies listeners + attributes + setNodeRef + transform style. onDragEnd: use arrayMove() to reorder state array.",
      demo:"DnD Kit sortable list — drag to reorder items" },
  ]},
  { id:"css", label:"Modern CSS Features", emoji:"🎨", items:[
    { name:"Container Queries",    avail:"builtin",desc:"Style by component size, not viewport",
      label:"@container queries",
      prompt:"Parent: container-type:inline-size (or size for both axes). Optional name: container-name:card. @container card (min-width:480px){ .card-inner { flex-direction:row; } } — component responds to its own box, not the viewport.",
      demo:"Container queries — same component layout adapts to its container width" },
    { name:"CSS :has() selector",  avail:"builtin",desc:"Parent selector via child state",
      label:"CSS :has() selector",
      prompt:"form:has(input:invalid) { border-color:red } — .card:has(img) { padding:0 } — nav:has(.active) { background:dark } — label:has(input:checked) { color:green }. The long-awaited parent selector. Supported in all modern browsers since 2023.",
      demo:":has() demo — form that styles itself based on input validity state" },
    { name:"CSS Scroll Snap",      avail:"builtin",desc:"Native snap scroll, zero JS",
      label:"scroll-snap CSS",
      prompt:"Container: overflow-x:scroll; scroll-snap-type:x mandatory; display:flex. Children: scroll-snap-align:start; flex-shrink:0; width:100% (or fixed px). For galleries: scroll-snap-type:x proximity. Add scrollbar-width:none to hide scrollbar.",
      demo:"CSS scroll snap carousel — no JavaScript required" },
    { name:"CSS color-mix()",      avail:"builtin",desc:"Mix colors natively in CSS",
      label:"color-mix()",
      prompt:"color-mix(in srgb, #6366f1 30%, white) — creates a 30% tint. color-mix(in oklch, blue, red) — perceptually smooth blend. Use for tints: color-mix(in srgb, var(--primary) 15%, transparent). Supported Chrome 111+, Safari 16.2+.",
      demo:"color-mix() demo — slider blends two colors in real time" },
    { name:"CSS text-wrap: balance",avail:"builtin",desc:"Auto-balances heading line lengths",
      label:"text-wrap:balance",
      prompt:"h1,h2,h3 { text-wrap:balance } — browser redistributes words so no line is drastically shorter than others. No more awkward single-word last lines. Also try text-wrap:pretty for body text to avoid orphaned words.",
      demo:"text-wrap:balance — before/after on multi-line headings" },
    { name:"CSS @starting-style",  avail:"builtin",desc:"Animate elements on first render",
      label:"@starting-style",
      prompt:"@starting-style { .dialog { opacity:0; transform:scale(0.95) translateY(-8px) } } — then .dialog { opacity:1; transform:none; transition:opacity 200ms, transform 200ms }. Animates the element on initial paint. No JS needed for enter animations.",
      demo:"@starting-style — elements animate on mount, zero JavaScript" },
    { name:"CSS view-transition",  avail:"builtin",desc:"Smooth DOM state transitions",
      label:"CSS view-transition",
      prompt:"document.startViewTransition(()=>{ updateDOMFunction() }). Each element with view-transition-name:'unique-name' morphs smoothly. @keyframes via ::view-transition-old and ::view-transition-new. Chrome 111+. Fallback: if(!document.startViewTransition) updateDirectly().",
      demo:"View transitions — smooth animated state changes without animation code" },
    { name:"CSS @layer",           avail:"builtin",desc:"Explicit cascade ordering",
      label:"@layer cascade",
      prompt:"@layer base, components, utilities; — @layer base { * { box-sizing:border-box } } @layer components { .btn { ... } } @layer utilities { .mt-4 { margin-top:1rem } }. Higher layers win. No more specificity wars. Unlayered styles win over all layers.",
    },
    { name:"CSS Nesting",          avail:"builtin",desc:"Native SCSS nesting, no preprocessor",
      label:"native CSS nesting",
      prompt:".card { background:white; &:hover { background:gray } & .title { font-weight:bold } @media(min-width:640px){ flex-direction:row } }. The & is the parent selector. Supported in all browsers since 2024. No build step needed.",
    },
    { name:"CSS aspect-ratio",     avail:"builtin",desc:"Maintain ratio without padding hacks",
      label:"aspect-ratio property",
      prompt:"aspect-ratio:16/9 — eliminates the padding-top percentage hack. Works with object-fit:cover on images. aspect-ratio:1 for square. Combines with width:100% for responsive. Also: contain-intrinsic-size for lazy-loaded unknown dimensions.",
    },
  ]},
  { id:"libs", label:"Bundled Libraries (React)", emoji:"📦", items:[
    { name:"lucide-react",  avail:"bundled",desc:"Icons",             label:"lucide-react",   prompt:"import { Settings, User, Bell, Search, ChevronRight, X, Plus } from 'lucide-react'" },
    { name:"recharts",      avail:"bundled",desc:"Charts",            label:"recharts",        prompt:"import { ResponsiveContainer, LineChart, Line, BarChart, Bar, XAxis, YAxis, CartesianGrid, Tooltip, Legend } from 'recharts'" },
    { name:"three (r128)",  avail:"bundled",desc:"3D graphics",       label:"three (r128)",    prompt:"import * as THREE from 'three' — no OrbitControls available. Use custom mouse event rotation or auto-rotate in RAF." },
    { name:"d3",            avail:"bundled",desc:"Data viz",          label:"d3",              prompt:"import * as d3 from 'd3'" },
    { name:"mathjs",        avail:"bundled",desc:"Math engine",       label:"mathjs",          prompt:"import * as math from 'mathjs' — math.evaluate('2^3 + sqrt(16)')" },
    { name:"lodash",        avail:"bundled",desc:"Utilities",         label:"lodash",          prompt:"import _ from 'lodash' — _.groupBy, _.sortBy, _.debounce, _.cloneDeep" },
    { name:"papaparse",     avail:"bundled",desc:"CSV parsing",       label:"papaparse",       prompt:"import Papa from 'papaparse' — Papa.parse(file,{header:true,complete:(r)=>setData(r.data)})" },
    { name:"xlsx",          avail:"bundled",desc:"Excel read/write",  label:"xlsx (SheetJS)",  prompt:"import * as XLSX from 'xlsx' — const wb=XLSX.read(arrayBuffer); const ws=wb.Sheets[wb.SheetNames[0]]; const data=XLSX.utils.sheet_to_json(ws)" },
    { name:"tone.js",       avail:"bundled",desc:"Web audio synth",   label:"tone.js",         prompt:"import * as Tone from 'tone' — const synth=new Tone.Synth().toDestination(); await Tone.start(); synth.triggerAttackRelease('C4','8n'). Must call Tone.start() in user gesture.",
      demo:"Tone.js demo — piano keys, UI click sounds, ambient loop" },
    { name:"mammoth",       avail:"bundled",desc:"Read .docx files",  label:"mammoth",         prompt:"import mammoth from 'mammoth' — mammoth.convertToHtml({arrayBuffer}).then(r=>setHtml(r.value))" },
    { name:"shadcn/ui",     avail:"bundled",desc:"UI components",     label:"shadcn/ui",       prompt:"import { Button } from '@/components/ui/button' import { Card,CardContent,CardHeader,CardTitle } from '@/components/ui/card' import { Badge } from '@/components/ui/badge'" },
  ]},
  { id:"na", label:"Not Available", emoji:"🚫", items:[
    { name:"localStorage / sessionStorage", avail:"unavailable",desc:"Silently fails. Use window.storage instead.",     label:"localStorage" },
    { name:"Framer Motion",                 avail:"unavailable",desc:"Not bundled. Use CSS keyframes.",                label:"Framer Motion" },
    { name:"WebSockets",                    avail:"unavailable",desc:"Not practical in sandbox.",                      label:"WebSockets" },
    { name:"Video Backgrounds",             avail:"unavailable",desc:"No video hosting. Use CSS animation.",           label:"video backgrounds" },
    { name:"IndexedDB",                     avail:"unavailable",desc:"Use window.storage instead.",                    label:"IndexedDB" },
    { name:"Arbitrary fetch() URLs",        avail:"unavailable",desc:"Only Anthropic API + cdnjs/esm.sh/unpkg/jsdelivr/Google Fonts.", label:"arbitrary fetch()" },
  ]},
],
  CONNECTIONS: [
  { title:"Stack visual effects — they're additive",
    text:"Aurora BG + glassmorphism cards + gradient text + staggered entrance + Google Font = one cohesive direction. You've been asking for them one at a time. Ask me to combine them.",
    demo:"Build a hero section with all of these combined: aurora gradient mesh background, glassmorphism card over it, gradient text headline, Space Grotesk from Google Fonts, staggered entrance animation on the card content" },
  { title:"Your MCP connectors can power artifacts",
    text:"You have Linear, Notion, Slack, Supabase, n8n, Todoist all connected. Pass them as mcp_servers in the artifact's embedded Claude API call. That artifact reads your actual data. It's an app, not a mockup.",
    demo:"Build an artifact that embeds a Claude API call with mcp_servers to my Notion connection — reads my 5 most recent Notion pages and displays them as cards inside the artifact" },
  { title:"Artifacts as persistent products",
    text:"window.storage + Claude API = a tool that remembers state and acts. Zero backend. You could ship a working productivity tool entirely inside an artifact today.",
    demo:"Build a persistent task tracker — window.storage saves tasks across sessions, Claude API suggests priorities on demand, no backend" },
  { title:"Tone.js is bundled — you've never used sound",
    text:"Tone.js is importable right now in React artifacts. Synth effects, UI feedback sounds, notification tones. A 20ms synth hit on button press changes how an interface feels entirely.",
    demo:"Tone.js artifact — interactive synth piano, button click sound effects, and a simple generative ambient loop" },
  { title:"The file pipeline is all bundled",
    text:"File upload → FileReader → base64 → Claude API document block → structured response. PDF, DOCX, images, CSVs — all inside one artifact. That's a real document analysis tool, deployable today.",
    demo:"File analysis artifact — drag-drop any file (PDF, image, CSV, DOCX), process with Claude API, return structured analysis inside the artifact" },
  { title:"Three bundled libraries = full data analysis tool",
    text:"PapaParse parses the CSV. recharts auto-generates the charts. Claude API surfaces the patterns. That's a complete analytics tool in one artifact with no external dependencies.",
    demo:"CSV analysis artifact — upload a CSV, PapaParse parses it, recharts generates charts automatically, Claude API surfaces key insights" },
  { title:"ECharts/AG Grid fill the gaps in bundled libs",
    text:"recharts can't do sankey diagrams, sunburst charts, or graph viz. AG Grid is what recharts data tables wish they were. These are one CDN line away.",
    demo:"ECharts artifact showing a chart type recharts cannot do — sankey, sunburst, or force-directed graph" },
  { title:"Voice input is native browser — no library",
    text:"Web Speech API: zero libraries, zero CDN. User speaks → transcript → Claude API → response. A voice-driven interface in 20 lines.",
    demo:"Voice input artifact — microphone button, Web Speech API transcription, sends to Claude API, streams response in real time" },
  { title:"Modern CSS replaces more JS than you think",
    text:"Scroll snap carousels, :has() parent selectors, @starting-style entrance animations, view transitions — all CSS, zero JavaScript. Every artifact so far could have cut 30% of its JS with these.",
    demo:"Build a demo showing 4 things modern CSS does without JavaScript: scroll snap carousel, :has() form styling, @starting-style entrance animation, CSS view transition between states" },
]
};
